version: '3.2'

services:
  web:
    image: nginx:1.17.6
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d         # your web configuration: docker/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs           # your https certs: docker/nginx/certs
      - app_static:/usr/share/nginx/html/static
      - app_resources:/usr/share/nginx/html/resources
    ports:
      - "8080:80"   # test
      #- "80:80"    # production
      #- "443:443"  # https
    depends_on:
      - app
      - worker-default
      - worker-high
    links:
      - app:dcrm-app
  app:
    build: .
    volumes:
      - app_static:/usr/src/app/static
      - app_resources:/usr/src/app/resources
      - app_temp:/usr/src/app/temp
      - ./.gnupg:/usr/src/app/.gnupg
    stdin_open: true
    tty: true
    links:
      - db:dcrm-db
      - redis:dcrm-redis
      - memcached:dcrm-memcached
    environment:
      PYTHONUNBUFFERED: 1
      DCRM_WORKER: none
    env_file:
      - ./DCRM/.env
  worker-default:           # if you need more `default` workers, duplicate this section
    build: .
    volumes:
      - app_static:/usr/src/app/static
      - app_resources:/usr/src/app/resources
      - app_temp:/usr/src/app/temp
      - ./.gnupg:/usr/src/app/.gnupg
    links:
      - db:dcrm-db
      - redis:dcrm-redis
      - memcached:dcrm-memcached
    environment:
      PYTHONUNBUFFERED: 1
      DCRM_WORKER: default  # worker priority
    env_file:
      - ./DCRM/.env
  worker-high:              # if you need more `high` workers, duplicate this section
    build: .
    volumes:
      - app_static:/usr/src/app/static
      - app_resources:/usr/src/app/resources
      - app_temp:/usr/src/app/temp
      - ./.gnupg:/usr/src/app/.gnupg
    links:
      - db:dcrm-db
      - redis:dcrm-redis
      - memcached:dcrm-memcached
    environment:
      PYTHONUNBUFFERED: 1
      DCRM_WORKER: high     # worker priority
    env_file:
      - ./DCRM/.env
  scheduler:
    build: .
    volumes:
      - app_static:/usr/src/app/static
      - app_resources:/usr/src/app/resources
      - app_temp:/usr/src/app/temp
      - ./.gnupg:/usr/src/app/.gnupg
    links:
      - db:dcrm-db
      - redis:dcrm-redis
      - memcached:dcrm-memcached
    environment:
      PYTHONUNBUFFERED: 1
      DCRM_WORKER: scheduler
    env_file:
      - ./DCRM/.env
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d         # your db configuration: docker/mysql/conf.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dcrm_root_password
      MYSQL_DATABASE: DCRM                       # important: should match `DCRM/settings.py`
      MYSQL_USER: dcrm                           # important: should match `DCRM/settings.py`
      MYSQL_PASSWORD: dcrm_user_password         # important: should match `DCRM/settings.py`
  redis:
    image: redis
    restart: always
  memcached:
    image: memcached
    restart: always

# your data will not lost until you clean these docker volumes
volumes:
  db_data:        # mysql database
  app_static:     # static files
  app_resources:  # packages
  app_temp:

